<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= esc($title ?? 'Report') ?></title>
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            color: #2d3748;
            background: #ffffff;
            font-size: 10pt;
            line-height: 1.5;
            padding: 10px;
        }
        .header {
            margin-bottom: 24px;
            border-bottom: 2px solid <?= esc($themeColor ?? '#3182ce') ?>;
            padding-bottom: 12px;
        }
        .title {
            font-size: 18pt;
            font-weight: 700;
            color: <?= esc($themeColor ?? '#2b6cb0') ?>;
            margin-bottom: 4px;
        }
        .subtitle {
            font-size: 10pt;
            color: #718096;
        }
        .meta {
            margin-top: 6px;
            font-size: 8pt;
            color: #a0aec0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        thead {
            display: table-header-group;
        }
        tr {
            page-break-inside: avoid;
        }
        th {
            background-color: <?= esc($themeColor ?? '#3182ce') ?>;
            color: #ffffff;
            font-weight: 600;
            text-align: left;
            padding: 8px 10px;
            font-size: 9pt;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9.5pt;
        }
        tbody tr:nth-child(even) {
            background-color: #f7fafc;
        }
        tfoot tr {
            background-color: #edf2f7;
            font-weight: 700;
            border-top: 2px solid #cbd5e0;
        }
        tfoot td {
            padding: 10px;
            border-bottom: none;
            color: #1a202c;
        }
        .text-left { text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 8pt;
            color: #a0aec0;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title"><?= esc($title) ?></h1>
        <?php if (!empty($subtitle)): ?>
            <p class="subtitle"><?= esc($subtitle) ?></p>
        <?php endif; ?>
        <p class="meta">Generated on <?= date('Y-m-d H:i:s') ?> | Total Records: <?= count($rows) ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <?php foreach ($columns as $col): ?>
                    <th class="text-<?= esc($col->align) ?>" <?= $col->width ? 'style="width: ' . esc($col->width) . '"' : '' ?>>
                        <?= esc($col->label) ?>
                    </th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($rows)): ?>
                <tr>
                    <td colspan="<?= count($columns) ?>" class="text-center" style="padding: 24px; color: #a0aec0;">
                        No records found.
                    </td>
                </tr>
            <?php else: ?>
                <?php foreach ($rows as $row): ?>
                    <tr>
                        <?php foreach ($columns as $col): ?>
                            <td class="text-<?= esc($col->align) ?>">
                                <?= $col->formatValue($row[$col->key] ?? null, $row) ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
        <?php if (!empty($aggregates) && !empty($rows)): ?>
            <tfoot>
                <tr>
                    <?php foreach ($columns as $index => $col): ?>
                        <td class="text-<?= esc($col->align) ?>">
                            <?php if (isset($aggregates[$col->key])): ?>
                                <?= esc($aggregates[$col->key]['label'] ?? '') ?> <?= $col->formatValue($aggregates[$col->key]['value'] ?? null) ?>
                            <?php elseif ($index === 0): ?>
                                Total Summary
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>

    <div class="footer">
        Generated by Jengo PDF Reporting Engine
    </div>
</body>
</html>
